local lush = require("lush")

return function(c)
  return lush(function(injected_functions)
    local sym = injected_functions.sym

    return {
      -- Core baseline
      Normal { fg = c.fg, bg = c.bg },
      NormalNC { fg = c.fg, bg = c.bg },
      NormalFloat { fg = c.fg, bg = c.bg },
      SignColumn { fg = c.fg, bg = c.bg },
      EndOfBuffer { fg = c.accent_dim_fg, bg = c.bg },

      -- Cursor / selection
      Visual { bg = c.selection_bg, gui = "underline" },
      CursorLine { bg = c.panel_alt_bg },

      -- Text classes
      Comment { fg = c.accent_hot_fg, gui = "italic" },
      Constant { fg = c.constant_fg },
      Identifier { fg = c.fg },
      Statement { fg = c.type_fg, gui = "italic" },
      PreProc { fg = c.type_fg, gui = "italic" },
      Type { fg = c.type_fg },
      Special { fg = c.type_fg, gui = "bold" },
      String { fg = c.string_fg },
      Function { fg = c.fg },
      pythonFunction { fg = c.fg },
      Keyword { fg = c.fg, gui = "italic" },
      Delimiter { fg = c.fg },
      Title { fg = c.title_fg, gui = "bold" },
      Operator { fg = c.fg },

      -- render-markdown.nvim: keep syntax fg from injected language, only tint code-block bg.
      RenderMarkdownCode { bg = c.panel_bg },
      RenderMarkdownCodeBorder { fg = c.panel_bg, bg = c.panel_bg },
      RenderMarkdownCodeInfo { bg = c.panel_bg, fg = c.muted_fg },
      RenderMarkdownCodeInline { bg = c.panel_bg },

      -- TypeScript: keep type usage styled as Type, but declarations as Normal.
      [sym"@lsp.type.interface"] = { fg = c.type_fg },
      [sym"@lsp.type.type"] = { fg = c.type_fg },
      [sym"@lsp.type.class"] = { fg = c.type_fg },
      [sym"@lsp.type.interface.typescript"] = { fg = c.type_fg },
      [sym"@lsp.type.type.typescript"] = { fg = c.type_fg },
      [sym"@lsp.type.function.typescript"] = { fg = c.fg },
      [sym"@lsp.type.class.typescript"] = { fg = c.type_fg },
      [sym"@function.call.typescript"] = { fg = c.fg },
      [sym"@function.call.tsx"] = { fg = c.fg },
      [sym"@variable"] = { fg = c.fg },
      [sym"@variable.parameter"] = { fg = c.fg },
      [sym"@function"] = { fg = c.fg },
      [sym"@function.call"] = { fg = c.fg },
      [sym"@function.method.call"] = { fg = c.constant_fg },
      [sym"@variable.member"] = { fg = c.constant_fg },
      [sym"@type"] = { fg = c.type_fg },
      [sym"@type.builtin"] = { fg = c.type_fg },
      [sym"@type.python"] = { fg = c.type_fg },
      [sym"@type.builtin.python"] = { fg = c.type_fg },
      [sym"@keyword"] = { fg = c.fg, gui = "italic" },
      [sym"@keyword.import"] = { fg = c.fg, gui = "italic" },
      [sym"@keyword.function"] = { fg = c.accent_hot_fg, gui = "bold" },
      [sym"@keyword.repeat"] = { fg = c.fg, gui = "italic" },
      [sym"@keyword.operator"] = { fg = c.fg, gui = "italic" },
      [sym"@keyword.conditional"] = { fg = c.fg, gui = "italic" },
      [sym"@keyword.return"] = { fg = c.fg, gui = "italic" },
      [sym"@operator"] = { fg = c.fg },
      [sym"@punctuation.delimiter"] = { fg = c.fg },
      [sym"@punctuation.bracket"] = { fg = c.accent_dim_fg },
      [sym"@function.python"] = { fg = c.fg },
      [sym"@function.call.python"] = { fg = c.fg },
      [sym"@method.python"] = { fg = c.fg },
      [sym"@method.call.python"] = { fg = c.fg },
      [sym"@variable.builtin.python"] = { fg = c.type_fg },
      [sym"@module.python"] = { fg = c.fg },
      [sym"@keyword.python"] = { fg = c.fg, gui = "italic" },
      [sym"@keyword.function.python"] = { fg = c.accent_hot_fg, gui = "bold" },
      [sym"@keyword.import.python"] = { fg = c.fg, gui = "italic" },
      [sym"@lsp.type.type.python"] = { fg = c.type_fg },
      [sym"@lsp.type.class.python"] = { fg = c.type_fg },
      [sym"@lsp.type.typeParameter.python"] = { fg = c.type_fg },
      [sym"@punctuation.bracket.typescript"] = { fg = c.accent_dim_fg },
      [sym"@punctuation.bracket.tsx"] = { fg = c.accent_dim_fg },
      [sym"@punctuation.bracket.python"] = { fg = c.accent_dim_fg },
      [sym"@lsp.mod.declaration"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.typemod.interface.declaration"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.typemod.type.declaration"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.typemod.class.declaration"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.mod.declaration.typescript"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.typemod.interface.declaration.typescript"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.typemod.type.declaration.typescript"] = { fg = c.fg, nocombine = true },
      [sym"@lsp.typemod.class.declaration.typescript"] = { fg = c.fg, nocombine = true },
      typescriptInterfaceName { fg = c.fg },
      typescriptTypeName { fg = c.fg },
      pythonBuiltin { fg = c.type_fg },
      pythonStatement { fg = c.fg },
      pythonDecorator { fg = c.accent_dim_fg, gui = "italic" },

      -- UI
      LineNr { fg = c.accent_dim_fg, bg = c.bg },
      StatusLine { fg = c.title_fg, bg = c.panel_bg },
      StatusLineNC { fg = c.muted_fg, bg = c.panel_bg, gui = "italic" },

      -- Diagnostics
      DiagnosticError { bg = c.diagnostic_error_bg, fg = c.fg, gui = "bold" },
      DiagnosticWarn { bg = c.diagnostic_warn_bg, fg = c.fg, gui = "bold" },
      DiagnosticInfo { bg = c.diagnostic_info_bg, fg = c.fg, gui = "bold" },
      DiagnosticHint { bg = c.diagnostic_hint_bg, fg = c.fg, gui = "bold" },
      DiagnosticOk { bg = c.diagnostic_ok_bg, fg = c.fg, gui = "bold" },
      DiagnosticUnderlineError { sp = c.diagnostic_error_bg, gui = "undercurl" },
      DiagnosticUnderlineWarn { sp = c.diagnostic_warn_bg, gui = "undercurl" },
      DiagnosticUnderlineInfo { sp = c.diagnostic_info_bg, gui = "undercurl" },
      DiagnosticUnderlineHint { sp = c.diagnostic_hint_bg, gui = "undercurl" },
      DiagnosticUnnecessary { fg = c.fg, sp = c.accent_dim_fg, gui = "italic,undercurl" },
      DiagnosticVirtualLinesError { bg = c.diagnostic_error_bg, fg = c.diagnostic_virtual_fg },
      DiagnosticVirtualLinesWarn { bg = c.diagnostic_warn_bg, fg = c.diagnostic_virtual_fg },
      DiagnosticVirtualLinesInfo { bg = c.diagnostic_info_bg, fg = c.diagnostic_virtual_fg },
      DiagnosticVirtualLinesHint { bg = c.diagnostic_hint_bg, fg = c.diagnostic_virtual_fg },
      DiagnosticVirtualLinesOk { bg = c.diagnostic_ok_bg, fg = c.diagnostic_virtual_fg },
      DiagnosticVirtualLinesFill { bg = c.diagnostic_error_bg, fg = c.diagnostic_virtual_fg },
      DiagnosticVirtualLinesFillError { bg = c.diagnostic_error_bg, fg = c.diagnostic_error_bg },
      DiagnosticVirtualLinesFillWarn { bg = c.diagnostic_warn_bg, fg = c.diagnostic_warn_bg },
      DiagnosticVirtualLinesFillInfo { bg = c.diagnostic_info_bg, fg = c.diagnostic_info_bg },
      DiagnosticVirtualLinesFillHint { bg = c.diagnostic_hint_bg, fg = c.diagnostic_hint_bg },
      Directory { fg = c.type_fg, gui = "italic" },
    }
  end)
end
